version: '3.5'

networks:
  ideafast-etl:
    external: true
  web:
    external: true

services:
  api:
    image: ideafast/wp3api:latest
    restart: always
    environment:
      APP_MODULE: api.main:api
      WP3API_AIRFLOW_PASS: ${WP3API_AIRFLOW_PASS}
    networks:
      - ideafast-etl
      - web
    labels:
      - "traefik.enable=true"

      # append next line to only allow specific endpoint for external requests
      # "&& PathPrefix(`/docs/update`)"
      - "traefik.http.routers.api.rule=Host(`api.wp3.ideafast.eu`)"

      - "traefik.http.routers.api.entrypoints=websecure"
      - "traefik.http.routers.api.tls=true"
      - "traefik.http.routers.api.tls.certresolver=leresolver"
