version: '3.5'

networks:
  ideafast-etl:
    external: true
  web:
    external: true

services:
  api:
    image: ideafast/wp3api:latest
    restart: always
    environment:
      APP_MODULE: api.main:api
      WP3API_AIRFLOW_PASS: ${WP3API_AIRFLOW_PASS}
    networks:
      - ideafast-etl
      - web
    labels:
      - "traefik.enable=true"
      # Only allow public traffic through the /docs/update endpoint
      - "traefik.http.routers.api.rule=Host(`api.localhost`) &&
        PathPrefix(`/docs/update`)"
      - "traefik.http.routers.api.entrypoints=websecure"
      - "traefik.http.routers.api.tls=true"
      - "traefik.http.routers.api.tls.certresolver=leresolver"
      # enforce basic auth to access this endpoint publically
      - "traefik.http.routers.api.middlewares=bauth"
      - "traefik.http.middlewares.bauth.basicauth.users=github_docs:${GITHUB_DO\
        CS_ENCRYPTPASS}"
