version: '3'

networks:
  web:
    external: true

services:
  limesurvey:
    image: crramirez/limesurvey:latest
    networks:
      - web
    volumes:
      - mysql:/var/lib/mysql
      - upload:/surveys/upload
    container_name: limesurvey
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.lime.rule=Host(`surveys.ideafast.eu`)"
      - "traefik.http.routers.lime.entrypoints=websecure"
      - "traefik.http.routers.lime.tls=true"
      - "traefik.http.routers.lime.tls.certresolver=leresolver"

volumes:
  mysql:
  upload:
