version: '3'

networks:
  web:
    external: true
  database:
    external: true

services:
  limesurvey:
    image: crramirez/limesurvey:latest
    networks:
      - web
      - database
    volumes:
      - mysql:/var/lib/mysql
      - upload:/app/upload
    container_name: limesurvey
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.snipeit.rule=Host(`surveys.ideafast.eu`)"
      - "traefik.http.routers.snipeit.entrypoints=websecure"
      - "traefik.http.routers.snipeit.tls=true"
      - "traefik.http.routers.snipeit.tls.certresolver=leresolver"

volumes:
  mysql:
  upload:
