version: '3'

networks:
  web:
    external: true
  database:
    external: true

services:
  snipe-mysql:
    image: mysql:5.6
    networks:
      - default
      - database
    env_file:
      - ./.snipeit.env
    volumes:
      - snipe_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    expose:
      - "3306"

  snipeit:
    image: snipe/snipe-it:v4.9.2
    networks:
      - web
      - database
    env_file:
      - ./.snipeit.env
    ports:
      - "3051:80"
    depends_on:
      - snipe-mysql

volumes:
  snipe_data:
