version: '2.4'

networks:
  web:
    external: true

services:
  jekyll:
    image: bretfisher/jekyll-serve
    volumes:
      - ./ideafast-devicesupportdocs-web:/site
    networks:
      - web
    container_name: devicessupportdocsweb
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.snipeit.rule=Host(`docs.localhost`)"
