version: '2.4'

networks:
  web:
    external: true

services:
  docs:
    image: nginx:alpine
    volumes:
      - ./docs:/usr/share/nginx/html/
    networks:
      - web
    container_name: docs
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.docs.rule=Host(`docs.localhost`)"
      - "traefik.http.routers.docs.middlewares=bauth"
