version: '2.4'

networks:
  web:
    external: true

services:
  docs:
    container_name: docs
    image: nginx:alpine
    restart: unless-stopped
    volumes:
      - ./conf:/etc/nginx/conf.d/
      - ./docs/_site:/usr/share/nginx/html/
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.docs.rule=Host(`docs.ideafast.eu`)"
      - "traefik.http.routers.docs.entrypoints=websecure"
      - "traefik.http.routers.docs.tls=true"
      - "traefik.http.routers.docs.tls.certresolver=leresolver"
      - "traefik.http.routers.docs.middlewares=bauth"
      - "traefik.http.middlewares.bauth.basicauth.usersfile=/usersfile"
