version: '3.8'

networks:
  web:
    external: true
  database:
    external: true

services:
  consumer_live:
    container_name: consumer_live
    image: ideafast/middleware-consumer:0.1.0-DEV
    restart: unless-stopped
    networks:
      - web
    env_file:
      - .consumer.live.env

  consumer_dev:
    container_name: consumer_dev
    image: ideafast/middleware-consumer:0.1.1-DEV
    restart: unless-stopped
    networks:
      - web
    env_file:
      - .consumer.dev.env

  dtransfer_live:
    container_name: dtransfer_live
    image: ideafast/middleware-dtransfer:0.1.2-DEV
    restart: unless-stopped
    networks:
      - web
      - database
    env_file:
      - .dtransfer.live.env
    volumes:
      - ./local:/app/local/
      - ./live/data:/app/data/

  dtransfer_dev:
    container_name: dtransfer_dev
    image: ideafast/middleware-dtransfer:0.1.3-DEV
    restart: unless-stopped
    networks:
      - web
      - database
    env_file:
      - .dtransfer.dev.env
    volumes:
      - ./local:/app/local/
      - ./dev/data:/app/data/
  
  mongodb:
    container_name: mongo
    image: mongo:4.4.3
    restart: unless-stopped
    command: [--auth]
    networks:
      - database
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db
    labels:
      - "traefik.enable=true"

volumes:
  mongodb: