version: '3.8'

networks:
  web:
    external: true
  database:
    external: true

services:
  consumer_live:
    container_name: consumer_live
    image: ideafast/middleware-consumer:0.1.0
    restart: unless-stopped
    networks:
      - web
    env_file:
      - .consumer.live.env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.consumer_live.rule=Host(`api.wp3.ideafast.eu`)"
      - "traefik.http.routers.consumer_live.entrypoints=websecure"
      - "traefik.http.routers.consumer_live.tls.certresolver=leresolver"

  consumer_dev:
    container_name: consumer_dev
    image: ideafast/middleware-consumer:0.1.0
    restart: unless-stopped
    networks:
      - web
    env_file:
      - .consumer.dev.env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.consumer_dev.rule=Host(`dev.api.wp3.ideafast.eu`)"
      - "traefik.http.routers.consumer_dev.entrypoints=websecure"
      - "traefik.http.routers.consumer_dev.tls.certresolver=leresolver"

  dtransfer_drm_dev:
    container_name: dtransfer_drm_dev
    image: ideafast/middleware-dtransfer:0.1.0-DRM
    networks:
      - database
    env_file:
      - .dtransfer.env
    volumes:
      - ./local:/app/local/

  mongodb:
    container_name: mongo
    image: mongo:4.4.3
    restart: unless-stopped
    command: [--auth]
    networks:
      - database
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db
    labels:
      - "traefik.enable=true"

volumes:
  mongodb: