version: '2'

networks:
  web:
    external: true
  database:
    external: true

services:
  zammad-nginx:
    environment:
      - VIRTUAL_HOST=support.ideafast.eu
    networks:
      - default
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.http.routers.zammad.rule=Host(`support.ideafast.eu`)"
      - "traefik.http.routers.zammad.entrypoints=websecure"
      - "traefik.http.routers.zammad.tls=true"
      - "traefik.http.routers.zammad.tls.certresolver=leresolver"
      - "traefik.http.routers.zammad.middlewares=csrfHeader"

  zammad-postgresql:
    ports:
      - "5432:5432"
    networks:
      - default
      - database
    labels:
      - "traefik.enable=true"
      - "traefik.tcp.routers.postgres.entrypoints=postgres"
