version: '2'

networks:
  web:
    external: true

services:
  zammad-nginx:
    environment:
      - VIRTUAL_HOST=support.localhost
    networks:
      - default
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.http.routers.zammad.rule=Host(`support.localhost`)"
